name: ECR Login test
on:
  workflow_dispatch:
jobs:
  build:
    name: ECR Login
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1

      - name: set credential helper
        id: docker-config
        run: |
          tmp_config=$(mktemp)
          jq \
            --arg key1 "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com" \
            --arg key2 "${{ secrets.AWS_ACCOUNT_ID }}.dkr-ecr.ap-northeast-1.on.aws" \
            --arg key3 "public.ecr.aws" \
            --arg value "ecr-login" \
            '.credHelpers |= (. + {($key1): $value, ($key2): $value, ($key3): $value})' \
            ~/.docker/config.json > $tmp_config
          mv $tmp_config ~/.docker/config.json

      - name: ECR Public pull
        run: |
          docker pull public.ecr.aws/docker/library/hello-world:latest
          docker run public.ecr.aws/docker/library/hello-world:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr-ecr.ap-northeast-1.on.aws/${{ secrets.ECR_REPO_NAME }}:1
          push: true
